name: Build page

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
       matrix:
         python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Setting list page
        run: |
          python generate_page.py
